/*
 * Pin src/menu/romcrc.c to tools/romcrc.py, so the two cannot drift apart quietly.
 *
 * There are two implementations of the bootcode's checksum because they do different jobs: the C
 * runs on the console and decides whether a ROM may be patched, and the Python runs over a whole
 * shelf on a PC in seconds and is how the algorithm was confirmed against real games in the first
 * place. Two implementations of an algorithm with no specification is exactly the situation where
 * one quietly stops agreeing with the other, and the failure is a ROM that does not boot.
 *
 * A synthetic image rather than a real one: the host suite may not assume anyone's ROMs are on
 * the machine, and arbitrary words exercise the accumulators far harder than a real boot segment,
 * which is mostly zeros and short constants. The carry counter t4 in particular never increments
 * on sparse data.
 *
 * The constants come from `tools/romcrc.py --vectors`, which builds the identical image from the
 * identical LCG.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "menu/romcrc.h"

static int checks;
static int failures;

static void check (bool ok, const char *what) {
    checks++;
    if (!ok) {
        failures++;
        printf("  FAIL: %s\n", what);
    }
}

/* The same generator tools/romcrc.py's synthetic() uses, producing the same big-endian words. */
static uint32_t *build_image (void) {
    size_t words = (ROMCRC_START + ROMCRC_LENGTH) / 4;
    uint32_t *rom = malloc(words * 4);
    uint32_t x = 0x12345678u;
    for (size_t i = 0; i < words; i++) {
        x = x * 1103515245u + 12345u;
        rom[i] = x;
    }
    return rom;
}

/* Native-endian words, per romcrc.h: the image above is already stored as host words, so this is
 * a straight copy and the byte order of the machine running the test never enters into it. */
static bool read_image (void *ctx, uint32_t offset, void *dst, size_t len) {
    const uint32_t *rom = ctx;
    if ((offset % 4) || (len % 4) || (offset + len > ROMCRC_START + ROMCRC_LENGTH)) {
        return false;
    }
    memcpy(dst, &rom[offset / 4], len);
    return true;
}

static bool short_read (void *ctx, uint32_t offset, void *dst, size_t len) {
    /* Fails once the checksum walks past the first chunk, to prove a read error is propagated
     * rather than silently producing a plausible number over whatever was in the buffer. */
    if (offset >= ROMCRC_START + 0x1000) {
        return false;
    }
    return read_image(ctx, offset, dst, len);
}

int main (void) {
    uint32_t *rom = build_image();

    /* generated by tools/romcrc.py --vectors */
    static const struct { cic_type_t cic; const char *name; uint32_t crc1, crc2; } vectors[] = {
        { CIC_x102, "6102", 0xA1B64E2Du, 0xD7B06D9Bu },
        { CIC_x103, "6103", 0x2304684Cu, 0xCD197358u },
        { CIC_x105, "6105", 0x475AF487u, 0x4CC984B0u },
        { CIC_x106, "6106", 0x11BA85BEu, 0x5AEDE63Bu },
    };

    for (size_t i = 0; i < sizeof(vectors) / sizeof(vectors[0]); i++) {
        uint32_t c1 = 0, c2 = 0;
        char what[64];
        bool ok = romcrc_compute(read_image, rom, vectors[i].cic, &c1, &c2);
        snprintf(what, sizeof(what), "CIC %s agrees with tools/romcrc.py", vectors[i].name);
        check(ok && c1 == vectors[i].crc1 && c2 == vectors[i].crc2, what);
        if (ok && (c1 != vectors[i].crc1 || c2 != vectors[i].crc2)) {
            printf("        %s: got %08x %08x, want %08x %08x\n",
                   vectors[i].name, c1, c2, vectors[i].crc1, vectors[i].crc2);
        }
    }

    /* 6101 and 7102 share 6102's seed, and the tail mix, so they must land on the same answer.
     * Written down because "they are the same" is the kind of thing a refactor stops being true
     * of, and nothing else in the suite would notice. */
    {
        uint32_t a1, a2, b1, b2, c1, c2;
        romcrc_compute(read_image, rom, CIC_x102, &a1, &a2);
        romcrc_compute(read_image, rom, CIC_6101, &b1, &b2);
        romcrc_compute(read_image, rom, CIC_7102, &c1, &c2);
        check(a1 == b1 && a2 == b2 && a1 == c1 && a2 == c2,
              "6101 and 7102 check out the same as 6102");
    }

    /* 6103 adds where the others xor, and 6106 multiplies. If those three collapsed into one the
     * vectors above would still all pass individually -- they are different seeds -- so the tail
     * mixes are pinned as distinct here. */
    {
        uint32_t a1, a2, b1, b2;
        romcrc_compute(read_image, rom, CIC_x103, &a1, &a2);
        romcrc_compute(read_image, rom, CIC_x106, &b1, &b2);
        check(a1 != b1 && a2 != b2, "6103 and 6106 do not share a final mix");
    }

    /* A CIC with no published seed must refuse rather than guess. Guessing produces a ROM that
     * does not boot, and the console cannot say why. */
    {
        uint32_t c1 = 0xDEADBEEF, c2 = 0xDEADBEEF;
        check(!romcrc_compute(read_image, rom, CIC_5167, &c1, &c2),
              "an unknown CIC is refused, not guessed at");
        check(!romcrc_compute(read_image, rom, CIC_UNKNOWN, &c1, &c2),
              "and so is CIC_UNKNOWN");
    }

    {
        uint32_t c1, c2;
        check(!romcrc_compute(short_read, rom, CIC_x102, &c1, &c2),
              "a read that fails part way through is reported, not averaged over");
        check(!romcrc_compute(NULL, rom, CIC_x102, &c1, &c2), "and so is no reader at all");
    }

    /* romcrc_verify() is the rule the menu actually runs on: recompute, compare with the header,
     * and patch nothing if they disagree. Both directions, because a verify that always said yes
     * would pass every other check in this file. */
    {
        uint32_t want1, want2, stored1 = 0, stored2 = 0;
        romcrc_compute(read_image, rom, CIC_x102, &want1, &want2);

        rom[0x10 / 4] = want1;
        rom[0x14 / 4] = want2;
        check(romcrc_verify(read_image, rom, CIC_x102, &stored1, &stored2),
              "a header that matches its contents verifies");
        check(stored1 == want1 && stored2 == want2, "and reports what the header held");

        rom[0x14 / 4] = want2 ^ 1;
        check(!romcrc_verify(read_image, rom, CIC_x102, NULL, NULL),
              "one wrong bit in CRC2 fails the check");
        rom[0x10 / 4] = want1 ^ 1;
        rom[0x14 / 4] = want2;
        check(!romcrc_verify(read_image, rom, CIC_x102, NULL, NULL),
              "and so does one wrong bit in CRC1");
    }

    /* The header sits at 0x10, below the checksummed window, so rewriting it must not change the
     * answer. If it did, patching the CRC would invalidate the CRC and no ROM could ever be
     * fixed up -- which is a thing that would only show up on hardware, as a black screen. */
    {
        uint32_t before1, before2, after1, after2;
        romcrc_compute(read_image, rom, CIC_x105, &before1, &before2);
        rom[0x10 / 4] = 0x5A5A5A5A;
        rom[0x14 / 4] = 0xA5A5A5A5;
        romcrc_compute(read_image, rom, CIC_x105, &after1, &after2);
        check(before1 == after1 && before2 == after2,
              "the checksum does not cover the header it is stored in");
    }

    /* 6105 mixes in bootcode at 0x750, which IS below the window. Changing it must change the
     * answer for 6105 and must not for anyone else -- the one place the two paths through the
     * accumulator loop can be told apart from outside. */
    {
        uint32_t a105, b105, a102, b102, c105, d105, c102, d102;
        romcrc_compute(read_image, rom, CIC_x105, &a105, &b105);
        romcrc_compute(read_image, rom, CIC_x102, &a102, &b102);
        rom[0x750 / 4] ^= 0xFFFFFFFF;
        romcrc_compute(read_image, rom, CIC_x105, &c105, &d105);
        romcrc_compute(read_image, rom, CIC_x102, &c102, &d102);
        check(a105 != c105 || b105 != d105, "6105 reads its own bootcode at 0x750");
        check(a102 == c102 && b102 == d102, "and 6102 does not");
    }

    /* The 6105 bootcode nop. boot/cheats.c writes a nop into DMEM word 486 -- byte 0x798, inside
     * the 0x750 window 6105 mixes in -- so a cheat-patched console computes a different checksum
     * from the one this file computes off a file. Replaying it must change the 6105 answer by
     * exactly that word and must change nothing for anyone else, and the word index must be the
     * one cheats.c actually writes. */
    {
        uint32_t a1, a2, b1, b2, c1, c2, d1, d2;
        check(ROMCRC_X105_NOP_WORD == 18, "the nop lands on word 18 of the 6105 window");
        romcrc_compute_ex(read_image, rom, CIC_x105, false, &a1, &a2);
        romcrc_compute_ex(read_image, rom, CIC_x105, true, &b1, &b2);
        check(a1 != b1 || a2 != b2, "replaying it changes the 6105 checksum");

        /* And it is the SAME as having zeroed that word in the image, which is the claim. */
        uint32_t saved = rom[(0x750 / 4) + ROMCRC_X105_NOP_WORD];
        rom[(0x750 / 4) + ROMCRC_X105_NOP_WORD] = 0;
        romcrc_compute_ex(read_image, rom, CIC_x105, false, &c1, &c2);
        rom[(0x750 / 4) + ROMCRC_X105_NOP_WORD] = saved;
        check(b1 == c1 && b2 == c2, "and it is exactly that word going to zero");

        romcrc_compute_ex(read_image, rom, CIC_x102, false, &a1, &a2);
        romcrc_compute_ex(read_image, rom, CIC_x102, true, &d1, &d2);
        check(a1 == d1 && a2 == d2, "and it does nothing to a CIC that has no such window");
    }

    free(rom);
    printf("  %d checks, %d failures\n", checks, failures);
    return failures ? 1 : 0;
}
