/*
 * What the vendored picojpeg accepts, pinned.
 *
 * The menu's JPEG support was measured against exactly one corpus -- the SD card that prompted
 * it, which is fifteen .jpeg and one .jpg, all baseline colour. Two variants a user can trivially
 * produce were never fed to it at all: grayscale, and progressive. Both are ordinary "Save As"
 * options in every image editor, so both will arrive on somebody's card.
 *
 * Measured here rather than reasoned about, because the two answers are different and only one of
 * them is a limitation:
 *
 *   grayscale    decodes, reporting m_comps == 1, which is the branch in jpeg_fill_band that
 *                replicates the single plane into R, G and B. Untested before this file.
 *   progressive  cannot be decoded at all. picojpeg says so in its own header --
 *                PJPG_UNSUPPORTED_MODE, "picojpeg doesn't support progressive JPEG's" -- and it
 *                fails at pjpeg_decode_init, before any buffer is allocated.
 *
 * This compiles the real vendored picojpeg. It does not compile image_decoder.c, which needs
 * libdragon surfaces; what it pins is the layer underneath, which is where both answers come
 * from. The image_decoder side of it is one branch: jpeg_init_err maps PJPG_UNSUPPORTED_MODE to
 * IMG_ERR_UNSUPPORTED and everything else to IMG_ERR_BAD_FILE.
 *
 * The JPEGs are generated by tools/hosttest/mkjpegs.py so nothing binary is committed.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <picojpeg.h>

static int checks = 0, failures = 0;

static void ok (int cond, const char *what) {
    checks++;
    if (!cond) {
        failures++;
        printf("  FAIL %s\n", what);
    }
}

static FILE *g_f;

static unsigned char need_bytes (unsigned char *buf, unsigned char n,
                                 unsigned char *actual, void *data) {
    (void)data;
    *actual = (unsigned char)fread(buf, 1, n, g_f);
    return 0;
}

/** @brief Init @p path at @p reduce; on success drain it and report the component count. */
static unsigned char probe (const char *dir, const char *name, int reduce,
                            int *comps, int *mcus, unsigned char *end) {
    char path[512];
    snprintf(path, sizeof(path), "%s/%s", dir, name);
    g_f = fopen(path, "rb");
    if (g_f == NULL) {
        printf("  FAIL cannot open %s\n", path);
        checks++; failures++;
        return 0xFF;
    }
    pjpeg_image_info_t ji;
    memset(&ji, 0, sizeof(ji));
    unsigned char e = pjpeg_decode_init(&ji, need_bytes, NULL, (unsigned char)reduce);
    if (e == 0) {
        *comps = ji.m_comps;
        int n = 0;
        unsigned char de;
        while ((de = pjpeg_decode_mcu()) == 0) {
            n++;
        }
        *mcus = n;
        *end = de;
    }
    fclose(g_f);
    return e;
}

int main (void) {
    const char *dir = getenv("TESTDIR");
    if (dir == NULL) {
        printf("TESTDIR not set\n");
        return 2;
    }

    /* Baseline colour, both chroma layouts. The 4:2:0 file has a 16x16 MCU and the 4:4:4 file an
     * 8x8 one, which is the difference jpeg_fill_band's bx_n/by_n loop exists to handle. */
    static const char *colour[] = { "baseline_420.jpg", "baseline_444.jpg" };
    for (int i = 0; i < 2; i++) {
        int comps = 0, mcus = 0;
        unsigned char end = 0;
        unsigned char e = probe(dir, colour[i], 0, &comps, &mcus, &end);
        ok(e == 0, colour[i]);
        ok(comps == 3, "colour reports three components");
        ok(end == PJPG_NO_MORE_BLOCKS, "colour drains to the end cleanly");
        ok(mcus > 0, "colour produced MCUs");
    }

    /* Grayscale. The point of the check is m_comps, because that is the flag jpeg_fill_band
     * reads to decide whether to replicate the luma plane. */
    {
        int comps = 0, mcus = 0;
        unsigned char end = 0;
        unsigned char e = probe(dir, "gray.jpg", 0, &comps, &mcus, &end);
        ok(e == 0, "grayscale baseline decodes");
        ok(comps == 1, "grayscale reports exactly one component");
        ok(end == PJPG_NO_MORE_BLOCKS, "grayscale drains to the end cleanly");
        ok(mcus > 0, "grayscale produced MCUs");
    }

    /* Grayscale through the DC-only path, which is what any card larger than a tile takes. */
    {
        int comps = 0, mcus = 0;
        unsigned char end = 0;
        unsigned char e = probe(dir, "gray.jpg", 1, &comps, &mcus, &end);
        ok(e == 0, "grayscale decodes DC-only too");
        ok(comps == 1, "grayscale still one component when reduced");
    }

    /* Progressive, colour and grayscale, at both reduce settings. All four must fail the same
     * way -- and specifically with UNSUPPORTED_MODE, because image_decoder keys on that value to
     * tell the user their file needs converting rather than that it is damaged. */
    static const char *prog[] = { "progressive.jpg", "gray_prog.jpg" };
    for (int i = 0; i < 2; i++) {
        for (int reduce = 0; reduce <= 1; reduce++) {
            int comps = 0, mcus = 0;
            unsigned char end = 0;
            unsigned char e = probe(dir, prog[i], reduce, &comps, &mcus, &end);
            ok(e == PJPG_UNSUPPORTED_MODE, "progressive is rejected as UNSUPPORTED_MODE");
        }
    }

    /* A truncated baseline file must NOT come back as UNSUPPORTED_MODE, or the distinction the
     * error code exists to make is worthless.
     *
     * And then the uncomfortable part, pinned because it is a real limitation and not a bug in
     * this test: picojpeg does not notice truncation AT ALL. A file cut in half inits fine,
     * yields the same 234 MCUs as the whole one, and ends with NO_MORE_BLOCKS -- because the
     * read callback simply reports zero bytes at EOF and the decoder carries on over the
     * resulting nothing. The tile decodes "successfully" and is part blank.
     *
     * Left alone deliberately. Detecting it means scanning back for an EOI marker, which some
     * encoders follow with padding, and that is a new way to reject valid art in exchange for
     * a cosmetic improvement on invalid art. It also self-heals: the atlas is keyed on path and
     * file size, so re-downloading the file misses the cache and decodes again. Asserted in
     * the affirmative so that if anyone ever does add truncation detection, this test tells
     * them exactly what they changed. */
    {
        int whole_mcus = 0, trunc_mcus = 0, comps = 0;
        unsigned char end = 0;
        unsigned char e = probe(dir, "baseline_420.jpg", 0, &comps, &whole_mcus, &end);
        ok(e == 0, "whole baseline decodes");

        e = probe(dir, "truncated.jpg", 0, &comps, &trunc_mcus, &end);
        ok(e != PJPG_UNSUPPORTED_MODE, "a truncated file is not reported as progressive");
        ok(e == 0, "a truncated file still opens");
        ok(trunc_mcus == whole_mcus, "truncation is invisible: same MCU count as the whole file");
        ok(end == PJPG_NO_MORE_BLOCKS, "truncation is invisible: still reports a clean end");
    }

    printf("  %d checks, %d failures\n", checks, failures);
    return failures == 0 ? 0 : 1;
}
