#!/usr/bin/env python3
"""
Compute the checksum IPL3 puts in a ROM header, and check that ROMs agree with their own.

    tools/romcrc.py /Volumes/SC64/roms/n64/*.z64      # check a shelf
    tools/romcrc.py --vectors                         # constants for the host test

## Why this exists

`src/menu/rompatch.c` changes two words of a game's boot segment before booting it, so that the
game installs the cheat engine's hook itself. Every retail IPL3 checksums ROM[0x1000..0x101000]
and compares the answer against CRC1/CRC2 in the header, so a patch without a recomputed checksum
is a console that stops dead -- black screen, no logo, no sound.

The algorithm is the bootcode's. It has no specification, it is six accumulators seeded per CIC
with three different final mixes, and a plausible-looking implementation that is subtly wrong
produces exactly that black screen. So it is written twice, here and in C, and pinned together by
tools/hosttest/test_romcrc.c over a synthetic image -- and separately checked against real ROMs,
which is what this script is for.

Measured on the 24 N64 ROMs of the reference card: 23 reproduce their stored checksum, across CIC
6101, 6102, 6103 and 6105. The twenty-fourth is Pokemon Stadium, whose CRC1 matches and whose CRC2
does not -- a header that disagreed with its own contents before anyone touched it. The menu's
rule handles that without needing to know which case it is: recompute the unpatched checksum
first, and if it does not match the header, do not patch the ROM.
"""

import argparse
import glob
import os
import struct
import sys
import zlib

M = 0xFFFFFFFF

# CRC32 of the 4,032-byte IPL3, the same identification tools/preamblescan.py uses.
IPL3_CRC = {
    0x6170A4A1: "6101", 0x90BB6CB5: "6102", 0x0B050EE0: "6103",
    0x98BC2C86: "6105", 0xACC8580A: "6106", 0x009E9EA3: "7102",
}

# Constants inside each bootcode. Not derivable -- only readable out of an IPL3, or confirmed
# against real ROMs, which is what the shelf run does.
SEED = {
    "6101": 0xF8CA4DDC, "6102": 0xF8CA4DDC, "7102": 0xF8CA4DDC,
    "6103": 0xA3886759, "6105": 0xDF26F436, "6106": 0x1FEA617A,
}

START = 0x1000
LENGTH = 0x100000

# CIC 6105 mixes in a 256-byte window of its own bootcode instead of the running accumulator.
X105_TABLE = 0x0750


def rol(v, b):
    b &= 31
    return ((v << b) | (v >> (32 - b))) & M if b else v


def crc(rom, cic):
    seed = SEED[cic]
    t1 = t2 = t3 = t4 = t5 = t6 = seed
    for i in range(START, START + LENGTH, 4):
        d = struct.unpack_from(">I", rom, i)[0]
        if ((t6 + d) & M) < t6:
            t4 = (t4 + 1) & M
        t6 = (t6 + d) & M
        t3 ^= d
        r = rol(d, d & 0x1F)
        t5 = (t5 + r) & M
        t2 ^= r if t2 > d else ((t6 ^ d) & M)
        if cic == "6105":
            t1 = (t1 + (struct.unpack_from(">I", rom, X105_TABLE + (i & 0xFF))[0] ^ d)) & M
        else:
            t1 = (t1 + ((t5 ^ d) & M)) & M

    if cic == "6103":
        return ((t6 ^ t4) + t3) & M, ((t5 ^ t2) + t1) & M
    if cic == "6106":
        return ((t6 * t4) + t3) & M, ((t5 * t2) + t1) & M
    return (t6 ^ t4 ^ t3) & M, (t5 ^ t2 ^ t1) & M


def normalise(data):
    """Return the ROM as big-endian bytes, or None if it is not a ROM at all."""
    if len(data) < START + LENGTH:
        return None
    magic = struct.unpack_from(">I", data, 0)[0]
    if magic == 0x80371240:
        return data
    if magic == 0x37804012:                                     # byte-swapped halfwords
        b = bytearray(data)
        b[0::2], b[1::2] = data[1::2], data[0::2]
        return bytes(b)
    if magic == 0x40123780:                                     # little-endian words
        b = bytearray(len(data))
        b[0::4], b[1::4], b[2::4], b[3::4] = data[3::4], data[2::4], data[1::4], data[0::4]
        return bytes(b)
    return None


def synthetic():
    """The host test's fixture: a deterministic 0x101000-byte image.

    An LCG rather than a real ROM, because the host suite may not assume anyone's ROMs are
    present, and because the point of this pinning is that the two implementations agree word for
    word -- which arbitrary bytes test better than a ROM whose contents are mostly zero.
    """
    out = bytearray(START + LENGTH)
    x = 0x12345678
    for i in range(0, len(out), 4):
        x = (x * 1103515245 + 12345) & M
        struct.pack_into(">I", out, i, x)
    return bytes(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("roms", nargs="*")
    ap.add_argument("--vectors", action="store_true",
                    help="print the synthetic-image constants tools/hosttest/test_romcrc.c pins")
    args = ap.parse_args()

    if args.vectors:
        rom = synthetic()
        print("/* generated by tools/romcrc.py --vectors */")
        for cic in ("6102", "6103", "6105", "6106"):
            c1, c2 = crc(rom, cic)
            print("{ 0x%08Xu, 0x%08Xu },   /* %s */" % (c1, c2, cic))
        return 0

    if not args.roms:
        ap.error("give some ROMs, or --vectors")

    ok = bad = skipped = 0
    for path in sorted(args.roms):
        name = os.path.basename(path)[:42]
        with open(path, "rb") as f:
            data = f.read(START + LENGTH)
        rom = normalise(data)
        if rom is None:
            print("%-42s NOT A ROM" % name)
            skipped += 1
            continue
        cic = IPL3_CRC.get(zlib.crc32(rom[0x40:0x1000]) & M)
        if cic is None:
            print("%-42s UNKNOWN CIC" % name)
            skipped += 1
            continue

        h1, h2 = struct.unpack_from(">II", rom, 0x10)
        g1, g2 = crc(rom, cic)
        match = (g1 == h1 and g2 == h2)
        ok += match
        bad += not match
        print("%-42s %-5s hdr %08x %08x  got %08x %08x  %s"
              % (name, cic, h1, h2, g1, g2, "ok" if match else "MISMATCH"))

    print("\n%d match, %d mismatch, %d skipped" % (ok, bad, skipped))
    return 0 if bad == 0 and skipped == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
