/**
 * @file inputscript.c
 * @brief Deterministic joypad replay for headless regression runs.
 * @ingroup dev
 */

#ifdef DEV_HARNESS

#include <libdragon.h>

#include "inputscript.h"

/* Generated by tools/mkinput.py into $(BUILD_DIR), which the Makefile adds to the include
 * path under DEV_HARNESS. When no INPUT_SCRIPT is named the generator still emits this header
 * with an empty program, so a DEV_HARNESS build without a script compiles and simply runs
 * interactively. */
#include "inputscript_generated.h"

static uint32_t frame = 0;
static size_t cursor = 0;
static iscript_action_t pending = ISCRIPT_ACT_NONE;
static const input_event_t *current = NULL;
static bool first_frame_of_event = false;
static bool recording = false;

/* Not sizeof: the generated array always holds at least one element so it is a legal C array,
 * and the generator reports the real count separately. */
#define EVENT_COUNT ((size_t)INPUTSCRIPT_EVENT_COUNT)

bool inputscript_active (void) {
    return EVENT_COUNT > 0 && cursor < EVENT_COUNT;
}

void inputscript_tick (void) {
    if (EVENT_COUNT == 0) {
        return;
    }

    /* Retire the event whose hold window has passed. Done before selecting, so a zero-hold
     * event still gets exactly one frame rather than being skipped outright. */
    if (current != NULL && frame >= (uint32_t)current->at_frame + current->hold_frames) {
        current = NULL;
        cursor++;
    }

    first_frame_of_event = false;

    if (current == NULL && cursor < EVENT_COUNT) {
        const input_event_t *next = &INPUTSCRIPT_EVENTS[cursor];
        if (frame >= next->at_frame) {
            current = next;
            first_frame_of_event = true;
            /* The record toggles are latched here rather than handed out through
             * inputscript_take_action(), because they describe a state that outlives the frame
             * they arrive on and every other action does not. */
            if (next->action == ISCRIPT_ACT_RECORD_ON) {
                recording = true;
            } else if (next->action == ISCRIPT_ACT_RECORD_OFF) {
                recording = false;
            } else if (next->action != ISCRIPT_ACT_NONE) {
                pending = (iscript_action_t)next->action;
            }
        }
    }

    frame++;
}

joypad_8way_t inputscript_direction (bool c_pad) {
    if (current == NULL) {
        return JOYPAD_8WAY_NONE;
    }
    uint8_t dir = c_pad ? current->cdir : current->dir;
    return (dir == 0xFF) ? JOYPAD_8WAY_NONE : (joypad_8way_t)dir;
}

bool inputscript_pressed (iscript_button_t button) {
    /* Edge-triggered to match joypad_get_buttons_pressed. Holding a button across frames must
     * not re-fire, or a single scripted "press a" would enter a menu and immediately act again
     * inside it. */
    return first_frame_of_event && current != NULL && (current->buttons & button) != 0;
}

iscript_action_t inputscript_take_action (void) {
    iscript_action_t a = pending;
    pending = ISCRIPT_ACT_NONE;
    return a;
}

bool inputscript_recording (void) {
    return recording;
}

#endif /* DEV_HARNESS */
